
predict/dl:
  convnet_4: 
    load_path: 'meta-learning-classfication/result/result_202405028/camely_all_4x/dl/convnet_4/2024-06-16-11-17-57'
    meta_epoch_for_predict: 0
  squeezenet1_0: 
    load_path: 'meta-learning-classfication/result/result_202405028/camely_all_4x/dl/squeezenet1_0/2024-06-15-11-35-35'
    meta_epoch_for_predict: 0
  resnet18:
    load_path: 'meta-learning-classfication/result/result_202405028/camely_all_4x/dl/resnet18/2024-06-15-11-39-18'
    meta_epoch_for_predict: 0
  resnet34:
    load_path: 'meta-learning-classfication/result/result_202405028/camely_all_4x/dl/resnet34/2024-06-15-11-39-46'
    meta_epoch_for_predict: 0
  resnet50:
    load_path: 'meta-learning-classfication/result/result_202405028/camely_all_4x/dl/resnet50/2024-06-15-21-52-18'
    meta_epoch_for_predict: 0
  vit_base_patch16_224:
    load_path: 'meta-learning-classfication/result/result_202405028/camely_all_4x/dl/vit_base_patch16_224/2024-06-15-12-15-30'
    meta_epoch_for_predict: 0
  vit_small_patch16_224:
    load_path: 'meta-learning-classfication/result/result_202405028/camely_all_4x/dl/vit_small_patch16_224/2024-06-15-12-47-49'
    meta_epoch_for_predict: 0
  mt_small_model_lymph:
    load_path: 'meta-learning-classfication/result/result_202405028/camely_all_4x/dl/mt_small_model_lymph/2024-06-15-13-54-22'
    meta_epoch_for_predict: 0
predict/imaml:
  mt_small_model_lymph:
    load_path: 'meta-learning-classfication/result/result_202405028/camely_all_4x/imaml/mt_small_model_lymph/2024-06-16-12-10-01'
    meta_epoch_for_predict: 1
predict/maml:
  mt_small_model_lymph:
    load_path: 'meta-learning-classfication/result/result_202405028/camely_all_4x/maml/mt_small_model_lymph/2024-06-16-12-11-38'
    meta_epoch_for_predict: 7
predict/reptile:
  mt_small_model_lymph:
    load_path: 'meta-learning-classfication/result/result_202405028/camely_all_4x/reptile/mt_small_model_lymph/2024-06-16-12-12-31'
    meta_epoch_for_predict: 4