predict/dl:
  convnet_4: 
    load_path: 'meta-learning-classfication/result/result_202405028/multi_centers_ffpe_4x/dl/convnet_4/2024-06-07-12-32-51'
    meta_epoch_for_predict: 0
  squeezenet1_0: 
    load_path: 'meta-learning-classfication/result/result_202405028/multi_centers_ffpe_4x/dl/squeezenet1_0/2024-06-15-18-33-59'
    meta_epoch_for_predict: 0
  resnet18:
    load_path: 'meta-learning-classfication/result/result_202405028/multi_centers_ffpe_4x/dl/resnet18/2024-06-16-10-21-55'
    meta_epoch_for_predict: 0
  resnet34:
    load_path: 'meta-learning-classfication/result/result_202405028/multi_centers_ffpe_4x/dl/resnet34/2024-06-15-18-35-48'
    meta_epoch_for_predict: 0
  resnet50:
    load_path: 'meta-learning-classfication/result/result_202405028/multi_centers_ffpe_4x/dl/resnet50/2024-06-15-21-51-29'
    meta_epoch_for_predict: 0
  vit_base_patch16_224:
    load_path: 'meta-learning-classfication/result/result_202405028/multi_centers_ffpe_4x/dl/vit_base_patch16_224/2024-06-15-18-36-12'
    meta_epoch_for_predict: 0
  vit_small_patch16_224:
    load_path: 'meta-learning-classfication/result/result_202405028/multi_centers_ffpe_4x/dl/vit_small_patch16_224/2024-06-07-12-31-57'
    meta_epoch_for_predict: 0
  mt_small_model_lymph:
    load_path: 'meta-learning-classfication/result/result_202405028/multi_centers_ffpe_4x/dl/mt_small_model_lymph/2024-06-07-12-36-51'
    meta_epoch_for_predict: 0
predict/imaml:
  mt_small_model_lymph:
    load_path: 'meta-learning-classfication/result/result_202405028/multi_centers_ffpe_4x/imaml/mt_small_model_lymph/2024-06-07-14-08-06'
    meta_epoch_for_predict: 0
predict/maml: 
  mt_small_model_lymph:
    load_path: 'meta-learning-classfication/result/result_202405028/multi_centers_ffpe_4x/maml/mt_small_model_lymph/2024-06-07-14-09-48'
    meta_epoch_for_predict: 2
predict/reptile:
  mt_small_model_lymph:
    load_path: 'meta-learning-classfication/result/result_202405028/multi_centers_ffpe_4x/reptile/mt_small_model_lymph/2024-06-07-14-11-11'
    meta_epoch_for_predict: 18