
predict/dl:
  convnet_4:
    load_path: 'result_thyroid_fuse_20250817/thyroid_fuse_micro/dl/convnet_4/pretrain_False/2025-08-20-12-06-17'
    meta_epoch_for_predict: 0
  squeezenet1_0:
    load_path: 'result_thyroid_fuse_20250817/thyroid_fuse_micro/dl/squeezenet1_0/pretrain_False/2025-08-18-12-30-16'
    meta_epoch_for_predict: 0
  resnet18:
    load_path: 'result_thyroid_fuse_20250817/thyroid_fuse_micro/dl/resnet18/pretrain_False/2025-08-18-11-52-08'
    meta_epoch_for_predict: 0
  resnet34:
    load_path: 'result_thyroid_fuse_20250817/thyroid_fuse_micro/dl/resnet34/pretrain_False/2025-08-19-15-38-14'
    meta_epoch_for_predict: 0
  resnet50:
    load_path: 'result_thyroid_fuse_20250817/thyroid_fuse_micro/dl/resnet50/pretrain_False/2025-08-18-11-56-50'
    meta_epoch_for_predict: 0
  vit_tiny_patch16_224:
    load_path: 'result_thyroid_fuse_20250817/thyroid_fuse_micro/dl/vit_tiny_patch16_224/pretrain_False/2025-08-20-12-06-53'
    meta_epoch_for_predict: 0
  vit_base_patch16_224:
    load_path: 'result_thyroid_fuse_20250817/thyroid_fuse_micro/dl/vit_base_patch16_224/pretrain_False/2025-08-19-14-50-42'
    meta_epoch_for_predict: 0
  vit_small_patch16_224:
    load_path: 'result_thyroid_fuse_20250817/thyroid_fuse_micro/dl/vit_small_patch16_224/pretrain_False/2025-08-19-13-45-31'
    meta_epoch_for_predict: 0
  mt_fuse_model:
    load_path: 'result_thyroid_fuse_20250817/thyroid_fuse_micro/dl/mt_fuse_model/pretrain_False/2025-08-21-11-01-25'
    meta_epoch_for_predict: 0
predict/imaml:
  mt_fuse_model:
    load_path: ''
    meta_epoch_for_predict: 
predict/maml:
  mt_fuse_model:
    load_path: ''
    meta_epoch_for_predict: 
predict/reptile:
  mt_fuse_model:
    load_path: 'result_thyroid_fuse_20250817/thyroid_fuse_micro/reptile/mt_fuse_model/pretrain_True/2025-08-25-12-22-50'
    meta_epoch_for_predict: 3